MuriloSantos.PedidosApp/Controllers/Api/ClientesController.cs
using MuriloSantos.PedidosApp.Application.Interfaces;
using MuriloSantos.PedidosApp.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MuriloSantos.PedidosApp.Controllers.Api
{
    public class ClientesController : ApiController
    {
        private readonly IClienteAppService _app;

        public ClientesController(IClienteAppService app)
        {
            _app = app;
        }

        public IEnumerable<ClienteViewModel> Get()
        {
            var clientes = _app.ListarClientes();
            return clientes;
        }
    }
}

MuriloSantos.PedidosApp/Controllers/Api/PedidosController.cs
using MuriloSantos.PedidosApp.Application.Interfaces;
using MuriloSantos.PedidosApp.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MuriloSantos.PedidosApp.Controllers.Api
{
    public class PedidosController : ApiController
    {
        private readonly IPedidoAppService _app;

        public PedidosController(IPedidoAppService app)
        {
            _app = app;
        }

        [HttpPut]
        public PedidoViewModel AddItem([FromBody]PedidoViewModel pedido, Guid id)
        {
            pedido = _app.AdicionarItem(pedido, id);
            return pedido;
        }

        [HttpDelete]
        public PedidoViewModel RemoveItem([FromBody]PedidoViewModel pedido, Guid id)
        {
            pedido = _app.RemoverItem(pedido, id);
            return pedido;
        }

        [HttpPost]
        public ValidationResultViewModel Gravar([FromBody]PedidoViewModel pedido)
        {
            var result = _app.GravarPedido(pedido);
            return result;
        }
    }
}

MuriloSantos.PedidosApp/Controllers/Api/ProdutosController.cs
using MuriloSantos.PedidosApp.Application.Interfaces;
using MuriloSantos.PedidosApp.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MuriloSantos.PedidosApp.Controllers.Api
{
    public class ProdutosController : ApiController
    {
        private IProdutoAppService _app;

        public ProdutosController(IProdutoAppService app)
        {
            _app = app;
        }

        public IEnumerable<ProdutoViewModel> Get()
        {
            var produtos = _app.ListarProdutos();
            return produtos;
        }
    }
}

MuriloSantos.PedidosApp/Controllers/PedidosController.cs
using MuriloSantos.PedidosApp.Application.Interfaces;
using MuriloSantos.PedidosApp.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuriloSantos.PedidosApp.Controllers
{
    public class PedidosController : Controller
    {
        public PedidosController()
        {

        }

        // GET: Pedidos
        public ActionResult CriarPedido()
        {
            return View();
        }
    }
}

MuriloSantos.PedidosApp/Views/Pedidos/CriarPedido.cshtml
@{
    ViewBag.Title = "Criar Pedido";
}

<h2>Pedido de Venda</h2>
<hr>

<form name="formPedido" ng-controller="CriarPedidoController">

    <div class="row alert alert-danger" ng-hide="validationResult == undefined || validationResult.IsValid">
        <ul>
            <li ng-repeat="erro in validationResult.Errors">{{erro}}</li>
        </ul>
    </div>

    <div class="row">
        
        <div class="col-lg-6">
            <fieldset class="form-inline">
                <label>Cliente:</label>
                <select class="form-control" ng-model="pedido.ClienteId">
                    <option>Selecione</option>
                    <option ng-repeat="cliente in clientes" value="{{cliente.Id}}">
                        {{cliente.Nome}}
                    </option>
                </select>
            </fieldset>
        </div>

       <div class="col-lg-6">
           <fieldset class="form-inline">
               <label>*Data Entrega:</label>
               <input type="date" class="form-control" ng-model="pedido.DataEntrega" required>
           </fieldset>
       </div>

    </div>

    <hr>
    <h4>Itens do Pedido</h4>

     <div class="row">
        <div class="col-lg-6">
            <fieldset class="form-inline">
                <label>Produto:</label>
                <select class="form-control" ng-model="produtoId">
                    <option value="">Selecione</option>
                    <option ng-repeat="produto in produtos" value="{{produto.Id}}">
                        {{produto.Descricao}}
                    </option>
                </select>
                <button type="button" class="btn btn-primary" ng-click="addItem()" ng-disabled="produtoId == ''">
                    <span class="glyphicon glyphicon-plus"></span> Adicionar
                </button>
            </fieldset>
        </div>
     </div>

    <br /><br />
   <div class="row">
      <div class="col-md-12">
          <table class="table-bordered">
              <thead>
                  <tr>
                      <th class="col-md-4">Produto</th>
                      <th class="col-md-2 text-right">Qtde</th>
                      <th class="col-md-2 text-right">Valor</th>
                      <th class="col-md-2 text-right">Valor Total</th>
                      <th class="col-md-2 text-center">Ação</th>
                  </tr>
              </thead>
              <tbody>
                  <tr ng-repeat="item in pedido.Itens">
                      <td class="col-md-4">{{item.DescricaoProduto}}</td>
                      <td class="col-md-2 text-right">{{item.Quantidade | number:2}}</td>
                      <td class="col-md-2 text-right">{{item.Valor | number:2}}</td>
                      <td class="col-md-2 text-right">{{item.ValorTotal | number:2}}</td>
                      <td class="col-md-2 text-center">
                          <button class="btn btn-xs btn-danger" ng-click="removeItem(item.ProdutoId)">
                              <span class="glyphicon glyphicon-trash"></span>
                          </button>
                      </td>
                  </tr>
              </tbody>
          </table>
      </div>
   </div>

    <hr />

    <div class="col-md-offset-5">
        <label>Total:</label>
        <label ng-bind="pedido.ValorTotal | number:2"></label>
    </div>

    <div class="row">
        <div class="col-md-offset-5">
            <button class="btn btn-success" ng-disabled="formPedido.$invalid" ng-click="save()">
                <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
            </button>
        </div>
    </div>

</form>

MuriloSantos.PedidosApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pedidos App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Criar Pedido", "CriarPedido", "Pedidos")</li>
                    <li>@Html.ActionLink("Consultar Pedidos", "Consultar", "Pedidos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div ng-app="PedidosApp" class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pedidos App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>